# Generated by Django 3.1.3 on 2020-11-07 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_auto_20201107_2318'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='amaenities',
            new_name='amenities',
        ),
    ]
